static {
	TRANSLATION_MAP.insert("seeds", "Seeds")
	TRANSLATION_MAP.insert("log", "Oak Log")
	TRANSLATION_MAP.insert("log:2", "")
	TRANSLATION_MAP.insert("log:1", "")
	TRANSLATION_MAP.insert("log_2:1", "")
	TRANSLATION_MAP.insert("log_2", "Dark Oak Log")
	TRANSLATION_MAP.insert("cobblestone", "Cobblestone")
	TRANSLATION_MAP.insert("rotten_flesh", "Rotten Flesh")
	TRANSLATION_MAP.insert("coal", "Coal")
	TRANSLATION_MAP.insert("bone", "Bone")
	TRANSLATION_MAP.insert("ink_sack:4", "")
	TRANSLATION_MAP.insert("redstone", "Redstone")
	TRANSLATION_MAP.insert("wheat", "Wheat")
	TRANSLATION_MAP.insert("pork", "Pork")
	TRANSLATION_MAP.insert("carrot_item", "Carrot")
	TRANSLATION_MAP.insert("leather", "Leather")
	TRANSLATION_MAP.insert("melon", "Melon")
	TRANSLATION_MAP.insert("pumpkin", "Pumpkin")
	TRANSLATION_MAP.insert("potato_item", "Potato")
	TRANSLATION_MAP.insert("feather", "Feather")
	TRANSLATION_MAP.insert("raw_chicken", "Raw Chicken")
	TRANSLATION_MAP.insert("mushroom_collection", "Mushroom Collection")
	TRANSLATION_MAP.insert("log:3", "")
	TRANSLATION_MAP.insert("sulphur", "Sulphur")
	TRANSLATION_MAP.insert("iron_ingot", "Iron Ingot")
	TRANSLATION_MAP.insert("gold_ingot", "Gold Ingot")
	TRANSLATION_MAP.insert("emerald", "Emerald")
	TRANSLATION_MAP.insert("slime_ball", "Slime Ball")
	TRANSLATION_MAP.insert("diamond", "Diamond")
	TRANSLATION_MAP.insert("string", "String")
	TRANSLATION_MAP.insert("spider_eye", "Spider Eye")
	TRANSLATION_MAP.insert("blaze_rod", "Blaze Rod")
	TRANSLATION_MAP.insert("nether_stalk", "Nether Stalk")
	TRANSLATION_MAP.insert("magma_cream", "Magma Cream")
	TRANSLATION_MAP.insert("netherrack", "Netherrack")
	TRANSLATION_MAP.insert("glowstone_dust", "Glowstone Dust")
	TRANSLATION_MAP.insert("quartz", "Quartz")
	TRANSLATION_MAP.insert("gravel", "Gravel")
	TRANSLATION_MAP.insert("ghast_tear", "Ghast Tear")
	TRANSLATION_MAP.insert("ender_pearl", "Ender Pearl")
	TRANSLATION_MAP.insert("ender_stone", "Ender Stone")
	TRANSLATION_MAP.insert("obsidian", "Obsidian")
	TRANSLATION_MAP.insert("sugar_cane", "Sugar Cane")
	TRANSLATION_MAP.insert("rabbit", "Rabbit")
	TRANSLATION_MAP.insert("sand", "Sand")
	TRANSLATION_MAP.insert("cactus", "Cactus")
	TRANSLATION_MAP.insert("ink_sack:3", "")
	TRANSLATION_MAP.insert("mutton", "Mutton")
	TRANSLATION_MAP.insert("clay_ball", "Clay Ball")
	TRANSLATION_MAP.insert("sponge", "Sponge")
	TRANSLATION_MAP.insert("raw_fish", "Raw Fish")
	TRANSLATION_MAP.insert("raw_fish:1", "")
	TRANSLATION_MAP.insert("prismarine_crystals", "Prismarine Crystals")
	TRANSLATION_MAP.insert("raw_fish:2", "")
	TRANSLATION_MAP.insert("raw_fish:3", "")
	TRANSLATION_MAP.insert("prismarine_shard", "Prismarine Shard")
	TRANSLATION_MAP.insert("ink_sack", "Ink Sack")
	TRANSLATION_MAP.insert("water_lily", "Water Lily")
	TRANSLATION_MAP.insert("ice", "Ice")
	TRANSLATION_MAP.insert("enchanted_egg", "Enchanted Egg")
	TRANSLATION_MAP.insert("enchanted_feather", "Enchanted Feather")
	TRANSLATION_MAP.insert("enchanted_raw_chicken", "Enchanted Raw Chicken")
	TRANSLATION_MAP.insert("egg", "Egg")
	TRANSLATION_MAP.insert("enchanted_snow_block", "Enchanted Snow Block")
	TRANSLATION_MAP.insert("enchanted_diamond", "Enchanted Diamond")
	TRANSLATION_MAP.insert("snow_ball", "Snow Ball")
	TRANSLATION_MAP.insert("enchanted_raw_beef", "Enchanted Raw Beef")
	TRANSLATION_MAP.insert("raw_beef", "Raw Beef")
	TRANSLATION_MAP.insert("enchanted_glowstone_dust", "Enchanted Glowstone Dust")
	TRANSLATION_MAP.insert("enchanted_lapis_lazuli", "Enchanted Lapis Lazuli")
	TRANSLATION_MAP.insert("enchanted_gold", "Enchanted Gold")
	TRANSLATION_MAP.insert("red_rose:6", "")
	TRANSLATION_MAP.insert("red_rose:2", "")
	TRANSLATION_MAP.insert("double_plant:1", "")
	TRANSLATION_MAP.insert("mithril_ore", "Mithril Ore")
	TRANSLATION_MAP.insert("gemstone_collection", "Gemstone Collection")
	TRANSLATION_MAP.insert("hard_stone", "Hard Stone")
	TRANSLATION_MAP.insert("sulphur_ore", "Sulphur Ore")
	
}